[package]
name = "traffic_generator"
version = "0.1.0"
authors = ["Emma Ramirez <ramirez.emma.g@gmail.com>"]

[dependencies]
hyper = "*"
rustc-serialize = "*"
rand = "*"
ws = "*"
env_logger = "*"

[dependencies.chrono]
version = "*"
features = ["rustc-serialize"]
